---
- name: create autostart directory
  file: path=/home/pi/.config/lxsession/LXDE-pi state=directory

- name: copy start script
  template: src=autostart dest=/home/pi/.config/lxsession/LXDE-pi/
  notify:
  - reboot
