---
- name: upgrade all apt packages
  apt: upgrade=full update_cache=yes

- name: Install {{item}}
  apt: pkg={{item}} state=installed
  sudo: yes
  with_items:
  - unclutter
  - imagemagick
  - iceweasel
  - xdotool
  - x11vnc
