---
- include: set_system_proxy.yml

- hostname: name={{ inventory_hostname }}

- include: install_packages.yml

- include: iceweasel_settings.yml

- include: copy_scripts.yml

- include: create_cron_jobs.yml

- include: create_autostart.yml
